""" migration 2

Revision ID: 66267db6bfed
Revises: 0f3c26dc5d17
Create Date: 2019-07-30 17:21:31.299030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66267db6bfed'
down_revision = '0f3c26dc5d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'body_html')
    # ### end Alembic commands ###
